// <auto-generated />
namespace RentalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EditedBirthdayDatatoCustomers21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedBirthdayDatatoCustomers21));
        
        string IMigrationMetadata.Id
        {
            get { return "201903251531443_EditedBirthdayDatatoCustomers21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
